[project]
name = "somnolenciaia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe==0.10.9",
    "opencv-python-headless>=4.12.0.88",
]
